language: node_js
node_js:
  - "14"

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version

install:
  - cd frontend && npm install
  - cd ../backend && npm install
  - docker-compose build

script:
  - docker-compose up -d
  - ./wait-for-it.sh db:3306 --timeout=30
  - docker-compose exec backend npm test
  - cd frontend && npm run test

after_script:
  - docker-compose down