version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    networks:
      - mi-red

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge