services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    networks:
      - mi-red

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mi-red

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3002"
    command: npm run serve
    depends_on:
      - backend
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge