services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    networks:
      - mi-red

  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mi-red

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge
